### PR TITLE
feat: expose fluentbit missing network options

### PR DESCRIPTION
**Pull request by aslafy-z**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | no
| License         | Apache 2.0

### What's in this PR?

Bump fluentbit to 1.8.12, see
https://fluentbit.io/announcements/v1.8.10/
https://fluentbit.io/announcements/v1.8.11/
https://fluentbit.io/announcements/v1.8.12/

Expose fluentbit missing network options in the Logging CRD
- `net.dns.mode`
- `net.dns.prever_ipv4` (new in fluentbit 1.8.12)
- `net.dns.resolver` (new in fluentbit 1.8.11)
- `net.source_address`
- `net.connect_timeout_log_error`  (new in fluentbit 1.8.12)

### Why?

I need to overwrite the default fluentbit value  `net.dns.mode` to TCP

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

**Review by ahma — APPROVED** [review]
Looks fine thanks!

**Comment by aslafy-z** [comment]
@ahma I dismissed the review since because I just added two more configuration values to the set:
- `net.dns.prever_ipv4` (new in fluentbit 1.8.12)
- `net.dns.resolver` (new in fluentbit 1.8.11)

**Comment by aslafy-z** [comment]
@ahma [1ca7e73](https://github.com/banzaicloud/logging-operator/pull/928/commits/1ca7e7368f505e07f85756226e876ce758d6e702) bumps fluentbit to 1.8.12.

**Review by ahma — APPROVED** [review]
LGTM Thanks

**Review by tarokkk — APPROVED** [review]

**Pull request merged**
