### PR TITLE
allow adding AWS instance metadata on fluentbit records

### LINKED ISSUE #346: make AWS instance metadata available in logs
**Is your feature request related to a problem? Please describe.**
When analyzing logs, it's useful to know what AWS region, or availability zone it's coming from. You could reverse engineer that by making the connection to the node, but it should be easier to get and filter by if needed.

**Describe the solution you'd like**
fluent-bit has a aws filter plugin.

**Describe alternatives you've considered**
copying labels from nodes to all pods would be a pain

**Additional context**

### PR DESCRIPTION
**Pull request by alexxed**
This is done through the fluent-bit aws filter plugin.

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #346
| License         | Apache 2.0

### What's in this PR?
This PR adds the fluentbit aws filter plugin. To make it possible, some renames on the existing kubernetesFilter had to be done.

Although a map of filter would be possible, at this moment I think it's safer to keep them separate.

### Why?
Adds AWS instance metadata to log records.

### Checklist

- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline (TODO)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by alexxed** [comment]
Test locally on a kind cluster, still needs tests on AWS to confirm the metadata is added. 

```
(⎈ |kubernetes-admin@logging:default)➜  logging-operator git:(add-fluentbit-filter-aws) ✗ k get secret logging-fluentbit -o jsonpath="{.data['fluent-bit\.conf']}" | base64 --decode


[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
    storage.path  /buffers

[INPUT]
    Name         tail
    DB  /tail-db/tail-containers-state.db
    Mem_Buf_Limit  5MB
    Parser  cri
    Path  /var/log/containers/*.log
    Refresh_Interval  5
    Skip_Long_Lines  On
    Tag  kubernetes.*

[FILTER]
    Name        kubernetes
    Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Tag_Prefix  kubernetes.var.log.containers
    Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_URL  https://kubernetes.default.svc:443
    Match  kubernetes.*
    Merge_Log  On

[FILTER]
    Name        aws
    imds_version  v1

[OUTPUT]
    Name          forward
    Match         *
    Host          logging-fluentd.default.svc
    Port          24240
    
    Retry_Limit   False
```

**Comment by alexxed** [comment]
Tested on aws, missed the `Match` property, will have to add it.

**Comment by pepov** [comment]
Great! In your tests I can't see the configuration block that resulted in `imds_version  v1`  but I suppose you defined it explicitly otherwise that should be v2.

**Comment by alexxed** [comment]
Oh, need to update the fluentbit image, this filter is really fresh, 20 days ago: https://github.com/fluent/fluent-bit/commit/28750ae9e36c2b8b198b12ecf5cbd59e504fbe18#diff-016a9b89c8ba36864b19e3f86e5efe66

**Comment by alexxed** [comment]
No release yet https://github.com/fluent/fluent-bit/releases , looks like this PR needs to wait for that.

**Comment by alexxed** [comment]
> Great! In your tests I can't see the configuration block that resulted in imds_version v1 but I suppose you defined it explicitly otherwise that should be v2.

Yes, I wanted to test that I can override it.

**Comment by alexxed** [comment]
PR that we wait a release for https://github.com/fluent/fluent-bit/pull/1795 and its associated issue https://github.com/fluent/fluent-bit/issues/1780

Once that is released, this needs a fluentbit bump:
```diff
diff --git a/pkg/sdk/api/v1beta1/logging_types.go b/pkg/sdk/api/v1beta1/logging_types.go
index 9adada5..4869ab0 100644
--- a/pkg/sdk/api/v1beta1/logging_types.go
+++ b/pkg/sdk/api/v1beta1/logging_types.go
@@ -232,7 +232,7 @@ func (l *Logging) SetDefaults() (*Logging, error) {
                        copy.Spec.FluentbitSpec.Image.Repository = "fluent/fluent-bit"
                }
                if copy.Spec.FluentbitSpec.Image.Tag == "" {
-                       copy.Spec.FluentbitSpec.Image.Tag = "1.3.6"
+                       copy.Spec.FluentbitSpec.Image.Tag = "1.3.7"
                }
                if copy.Spec.FluentbitSpec.Image.PullPolicy == "" {
                        copy.Spec.FluentbitSpec.Image.PullPolicy = "IfNotPresent"
```

**Comment by alexxed** [comment]
This will most likely need to wait for the next minor fluent bit release, as the aws plugin is a feature, so 1.4.0.

**Comment by alexxed** [comment]
fluentbit 1.4 is out, this can be actioned, looking into it.

**Comment by alexxed** [comment]
Needs testing on AWS, don't just merge yet.

**Comment by alexxed** [comment]
Tested on a banzai eks cluster, looks fine:

```json
{
	"timestamp": 1585596693995,
	"log": "2020-03-30T19:31:33.995152Z\tinfo\twatchFileEvents: \"/etc/certs\": MODIFY|ATTRIB\n",
	"stream": "stdout",
	"time": "2020-03-30T19:31:33.995393362Z",
	"kubernetes": {
		"pod_name": "...",
		"namespace_name": "backyards-system",
		"pod_id": "...",
		"labels": {
			"...": "..."
		},
		"annotations": {
			"...": "..."
		},
		"host": "ip-....ec2.internal",
		"container_name": "istio-proxy",
		"docker_id": "...",
		"container_hash": "istio/proxyv2@sha256:9ba9de87d660767a2147f786040a8fe29ebb3b335742d3c95257ab82a33b8415",
		"container_image": "istio/proxyv2:1.4.0"
	},
	"az": "us-east-1a",
	"ec2_instance_id": "i-..."
}
```

**Comment by alexxed** [comment]
This is good to be merged from my point of view.

**Comment by ahma** [comment]
@alexxed Could you please send a "blank" commit to trigger the CI? There is some GH , Circle communication issue again.

**Comment by alexxed** [comment]
> @alexxed Could you please send a "blank" commit to trigger the CI? There is some GH , Circle communication issue again.

No luck.

**Comment by alexxed** [comment]
Ok, it kicked in a bit later, failed because I didn't run make/make test after a string update. Trying again.

**Pull request merged**
