### PR TITLE
[WIP] Add Windows support

### PR DESCRIPTION
**Pull request by nickgerace**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | #656, https://github.com/rancher/rancher/issues/28721
| License         | Apache 2.0

### What's in this PR?
(Adding more information soon) This PR adds logging support for Windows nodes. We may want to skip the fluentd configcheck for Windows altogether, but for now, it's scheduled to only run on Linux nodes.

### Additional context

This PR was based on previous experiences with Rancher projects using Windows.

- Rancher's logging stack before using the Logging Operator
  - https://github.com/rancher/system-charts/tree/dev-v2.5/charts/rancher-logging/0.2.3/charts/fluentd/charts/fluentd-windows
  - https://github.com/rancher/fluentd
  - https://github.com/rancher/fluentd/tree/master/scripts/windows
  - https://github.com/rancher/fluentd/tree/master/package/windows
- Rancher Fleet running only the "agent" on Windows nodes, and all other components on Linux nodes
  - https://github.com/rancher/fleet
  - https://github.com/rancher/fleet/blob/master/package/Dockerfile-windows.agent
  - https://github.com/rancher/fleet/blob/master/package/README.md
  - https://github.com/rancher/fleet-examples/tree/master/multi-cluster/windows-helm

### Checklist

*This is a work in progress.*

- [ ] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by ahma** [comment]
Hi @nickgerace!
First of all, thanks for your contribution.
Sadly I didn't mention your [issue](https://github.com/banzaicloud/logging-operator/issues/656) in our [PR](https://github.com/banzaicloud/logging-operator/pull/665) and because of this, you didn't get the information that we are working on your problem.
Sorry about that.
So, we had good progress on this, but now we have an issue with the fluent-bit [windows/amd64](https://github.com/fluent/fluent-bit/issues/2588) container. There isn't any official support for that in the fluent dockerhub. 
We made our [build](https://hub.docker.com/r/banzaicloud/fluentbit/tags?page=1&ordering=last_updated) from the official win-docker [file,](https://github.com/fluent/fluent-bit/blob/master/Dockerfile.windows) but of course, it's not working by default ...
Now we are working on this issue, but because we don't have too strong knowledge in the containerized windows world and especially with the debugging this isn't looking now an easy trip...
If you could help us with this issue it would be great. 
Thanks!

**Comment by nickgerace** [comment]
Hi @ahma! Thank for the update and it's exciting to see your progress. I'd be happy to help.
What does the new `nodeAgent` do exactly? It appears to be a controller that creates a fluentbit daemonset (among other required resources), but I'm curious what functionality does `nodeAgent` give that the core operator cannot already do?

**Comment by ahma** [comment]
@nickgerace, Yeah, you're right. 
Now you can define multiple fluentbit daemonsets whith the nodeAgent deffinition. e.g.:
```
nodeAgents:
  - name: winagent
    type: windows
    nodeAgentFluentbit:
      metrics:
        serviceMonitor: false
        prometheusAnnotations: true
  - name: linuxagent
    nodeAgentFluentbit:
      metrics:
        serviceMonitor: false
        prometheusAnnotations: false
```

In long term, it could be useful if we want to support not just fluent-bit but for example promtail, or anything else. 
A little status update:
The latest 1.6.5 Windows image seems to work now. Our next problem is that the fluent-bit can not catch any container logfile update under the /var/log/containers/. The route cause of the problem could be some symlink following miss function, but that is just an early guess from me.

**Comment by nickgerace** [comment]
Closing in favor of https://github.com/banzaicloud/logging-operator/pull/665
Thank you for the explanation @ahma. I've been using the builds from that branch with my clusters. Seems like it is close!

**Pull request closed without merging**
