### PR TITLE
add principal and keytab to kafka output

### PR DESCRIPTION
**Pull request by bryce-wilkinson-443**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #https://github.com/banzaicloud/logging-operator/issues/1058 
| License         | Apache 2.0

### What's in this PR?
Add principal and Keytab fields to Output and Cluster Output CRD's

### Why?
These fields are necessary if the kafka cluster is using kerberos

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### To Do

- [x] Test

### CODE REVIEW

**Review by siliconbrain — DISMISSED** [review]
lgtm

**Comment by siliconbrain** [comment]
@bryce-wilkinson-443 Please run `make generate` to regenerate the VFS embedding the manifests and push the changes. That should fix the build.

**Review by ahma — DISMISSED** [review]
Thanks @bryce-wilkinson-443 lgtm

**Comment by ahma** [comment]
@bryce-wilkinson-443 could you please run the `make generate` ?

**Comment by bryce-wilkinson-443** [comment]
Thanks I have ran make generate and pushed however it still seems to be failing at the diff stage

**Comment by siliconbrain** [comment]
@bryce-wilkinson-443 Because you've merged from master and didn't run `make generate` again 😄 Now, you should run
```sh
make generate
make manifests
make generate
```
I know, it's a little convoluted, but that's how it is 🤷

**Comment by siliconbrain** [comment]
@bryce-wilkinson-443 you're still missing a `go fmt` 🙂

**Comment by bryce-wilkinson-443** [comment]
Thank you

**Review by siliconbrain — DISMISSED** [review]

**Review by ahma — APPROVED** [review]

**Comment by bryce-wilkinson-443** [comment]
Thanks for all your help, I have confirmed it's working. I tried to squash a few commits to clean it up. But unable too for some reason. 


PR is now ready to merge

**Comment by siliconbrain** [comment]
@bryce-wilkinson-443 we're just waiting for you to sign the CLA

**Comment by bryce-wilkinson-443** [comment]
Thanks, CLA has been signed

**Review by ahma — APPROVED** [review]

**Pull request merged**
