### PR TITLE
GROK custom_pattern_path from secret

### PR DESCRIPTION
**Pull request by petergvizd**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
- GROK custom_pattern_path mounting from secret
- Added enableMsgpackTimeSupport option to fluentd system
- Added GROK support to multi_format parser

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Review by siliconbrain — APPROVED** [review]
lgtm

**Review by ahma — DISMISSED** [review]
lgtm

**Review by siliconbrain — APPROVED** [review]

**Comment by ahma** [comment]
@petergvizd sadly this is still broken 😞

**Comment by petergvizd** [comment]
Hello @ahma , sorry for silly question, what exactly is broken?

**Comment by ahma** [comment]
@petergvizd  this is a good question ... I'm seeing this
Screenshot 2022-07-19 at 13 25 19

**Comment by petergvizd** [comment]
interesting I am seeing this 😄 
Screenshot 2022-07-19 at 13 27 14

**Comment by petergvizd** [comment]
@ahma should I try to create new PR with these changes?

**Comment by ahma** [comment]
> @ahma should I try to create new PR with these changes?

@petergvizd if this is not a problem for you, please try it.

**Comment by ahma** [comment]
@petergvizd wait a minute, pls check again your forked master branch I think this is out of sync.

**Comment by petergvizd** [comment]
@ahma , yes it was behind but I synced it and merge to branch, are you still seeing same issue?

**Comment by petergvizd** [comment]
@ahma , it was already there, now I tried to rebase it, please let me know how it looks on your end

**Review by ahma — APPROVED** [review]

**Pull request merged**
