### PR TITLE
feat: add transport field to forwardOutput

### PR DESCRIPTION
**Pull request by cyril-corbon**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | no tickets related
| License         | Apache 2.0

### What's in this PR?

add transport field to forwardOutput.

### Why?

This allow fluentd forward output in tls
source: https://docs.fluentd.org/output/forward#how-to-connect-to-a-tls-ssl-enabled-server

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### To Do

- [x] If the PR is not complete but you want to discuss the approach, list what remains to be done here

### CODE REVIEW

**Review by ahma — APPROVED** [review]
lgtm Thanks @cyril-corbon

**Comment by ahma** [comment]
> 

yes, but you need to run a `make generate` this'll fix the build issue

**Comment by cyril-corbon** [comment]
done and all the check succeeded 👌

**Comment by ahma** [comment]
@cyril-corbon could you please update the pr?

**Comment by cyril-corbon** [comment]
> @cyril-corbon could you please update the pr?

done should I squash my commits ?

**Review by tarokkk — APPROVED** [review]
LGTM

**Comment by ahma** [comment]
Thanks @cyril-corbon !

**Pull request merged**
