### PR TITLE
Add support for net config options in fluentbit

### PR DESCRIPTION
**Pull request by worr**
fluentbit offers a few very useful network-related config tunables in the `net`
namespace of their configuration.

One of the more useful for active kubernetes clusters is the new
`net.keepalive_max_recycle` option, which will discard keepalive connections
after they've sent a configured number of messages (added in 1.6.2:
https://fluentbit.io/announcements/v1.6.2/).

Under the old behavior, an active kubernetes cluster could have extremely
long-living fluentbit -> fluentd connections, leading to uneven load on fluentd
instances. The `net.keepalive_max_recycle` option can be used to cycle these
connections so that we keep the distribution of fluentbit's to fluentd's more
even.

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
As explained in the commit message, this exposes fluentbit net options, and bumps the version of fluentbit so that we have a very useful network option exposed to us.

### Why?
We had found in our high-volume clusters that load to fluentd's was very lopsided after a long period of time. While this could be mitigated by bouncing all fluentbits, exposing useful network options makes it a lot easier to prevent this through configuration.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### To Do

More documentation *could* be added to the helm charts. However, since I didn't see a place for documentation for parameters like `positiondb` or `bufferStorageVolume`, I've followed suit with the `net` options. If necessary, I can provide more documentation.

### CODE REVIEW

**Comment by pepov** [comment]
Hey, nice addition! I think if we document default values, then we can simply set them in case the field is nil and avoid the XYZset boolean helper variables.

**Comment by worr** [comment]
I tried to avoid doing that specifically because theoretically, fluent-bit can change their defaults at any time, so defaults set here could lag behind their changes.

The flipside of this is that we could benefit from setting more kubernetes-specific defaults, like setting `net.keepalive_max_recycle`.

For now, I'll set the current fluent-bit defaults.

**Comment by pepov** [comment]
My point was that if we document defaults explicitly we may drift away actual fluentbit defaults over time. I'm not against either options anyways.

**Comment by worr** [comment]
Ahh, sorry, I misread. I'll leave the diff as-is then.

**Review by pepov — APPROVED** [review]

**Review by ahma — APPROVED** [review]
Great job thanks!

**Pull request merged**
