### PR TITLE
Add component label to fluentd pods and service selector

### PR DESCRIPTION
**Pull request by eddycharly**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no

### What's in this PR?

This pull request adds a `component` label to fluentd pods and service selector.

Without the label, the service considers the pod used to check config as a valid target (as the labels of the pod match the service selector).

With the `component` label, only the pods from the fluentd statefullset match the fluentd service.

### CODE REVIEW

**Comment by pepov** [comment]
@eddycharly thanks for pointing this out and for the fix! I think we want to use an officially recommended k8s label for this, just give us a little time to think this through!

**Comment by eddycharly** [comment]
No problem, i was thinking `component` was not perfect too. Maybe something like `app.kubernetes.io/component` ? ;-)

**Comment by pepov** [comment]
exactly and I've just double checked we don't use it anywhere so let's be it!

**Comment by eddycharly** [comment]
Done, i made the component part of the contract, looks cleaner and less error prone.

**Pull request merged**
