### PR TITLE
feat(fluentbit): add DB_Locking / DB_Journal_Mode parameter to InputTail

### PR DESCRIPTION
**Pull request by cyril-corbon**
Signed-off-by: Cyril Corbon <corboncyril@gmail.com>

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets |
| License         | Apache 2.0

### What's in this PR?

- add to inputTail struct the following parameter : 
  - DB_Locking 
  - DB_Journal_Mode

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Review by siliconbrain — APPROVED** [review]
lgtm

**Review by ahma — DISMISSED** [review]
lgtm

**Comment by cyril-corbon** [comment]
FYI I just rebase the pr 😃

**Review by siliconbrain — APPROVED** [review]

**Review by ahma — APPROVED** [review]
lgtm

**Pull request merged**
