### PR TITLE
Add support for OpenShift SCC

### LINKED ISSUE #1166: Add support for Openshift SCC
**Is your feature request related to a problem? Please describe.**
Whenever we need to deploy Logging Operator to OpenShift we need to deploy SCC separately for privileged Fluentbit (OpenShift doesn't support PSP)

**Describe the solution you'd like**
It would be nice if we can deploy SCC with the chart.

**Describe alternatives you've considered**
Deploying SCC separately

**Additional context**
Opening a PR soon.

### PR DESCRIPTION
**Pull request by aelbarkani**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #1166
| License         | Apache 2.0

### What's in this PR?
Add the possibility to deploy an SCC in OpenShift in order to allow Fluentbit to run in privileged mode.

### Why?
Solves #1166, to avoid deploying SCC separately.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by ahma** [comment]
@aelbarkani Could you update this pr, please?

**Comment by aelbarkani** [comment]
@ahma done !

**Review by ahma — APPROVED** [review]
lgtm

**Comment by ahma** [comment]
@aelbarkani Sorry, but we still have a conflict with this. Could you check that, please?

**Comment by aelbarkani** [comment]
are you sure @ahma ? I'm seeing this:

image

**Comment by ahma** [comment]
Screenshot 2023-02-01 at 14 55 12

**Comment by pepov** [comment]
Yes, it seems it has been lost during the migration from the separate charts to the single logging-operator chart. I beleive we can add this back into the chart if still needed.

**Pull request merged**
