### PR TITLE
added log_group_name_key attribute

### PR DESCRIPTION
**Pull request by dududko**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
Added `log_group_name_key` to CloudwatchOutput struct.

### Why?
This attribute is mentioned in documentation, but it does not present in the code.

### Checklist

- [x ] User guide and development docs updated (if needed)

### CODE REVIEW

**Comment by ahma** [comment]
Thanks for your fix @dududko . Could you please run the `make check-diff` command. It would be great too if you could add yourself to the list of adopters.

**Comment by pepov** [comment]
@dududko you should run `make generate manifests` in case there is a change in crds and commit the generated changes as well

**Comment by pepov** [comment]
@dududko could you please also rebase on the latest master?

**Comment by dududko** [comment]
Guys, you need to decide which strategy you are using in this repo, rebase or merge :-)

**Pull request merged**
