### PR TITLE
chore: move default images repositories and tags to globals

### PR DESCRIPTION
**Pull request by aslafy-z**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | none
| License         | Apache 2.0

### What's in this PR?

Move default fluentd sidecar images to external global variables

### Why?

So it ease readability of the current supported images for a given version of logging operator

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

### CODE REVIEW

**Review by ahma — APPROVED** [review]
lgtm Thanks @aslafy-z

**Review by siliconbrain — APPROVED** [review]
thx 👍

**Comment by ahma** [comment]
@aslafy-z could you please update the pr ?

**Comment by aslafy-z** [comment]
@ahma I just rebased the pull request.

**Comment by ahma** [comment]
@aslafy-z Great thanks!

**Pull request merged**
